# Generated by Django 5.0.1 on 2024-04-07 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myusers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('note', models.ManyToManyField(to='notesapp.note')),
            ],
        ),
    ]
