# Generated by Django 5.0.1 on 2024-04-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_noteaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteAccess',
        ),
    ]
