# Generated by Django 5.0.1 on 2024-04-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_delete_noteaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creater',
            new_name='creator',
        ),
    ]
