# Generated by Django 5.0.1 on 2024-04-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0005_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
